### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dcz-self** [bonsairobo/feldspar-editor#1]
Hi,
I found this project quite useful, but now (already after I started hacking), I noticed that there's no license information attached.

Would you mind adding some? I'll reciprocate by posting my sources :)

Cheers!

**Comment by bonsairobo** [comment]
@dcz-self Yea sure. It'll be MIT/Apache2. Just FYI this project is moving directly into [feldspar](https://github.com/bonsairobo/feldspar) and undergoing a partial rewrite. So stay tuned for updates there.

**Comment by bonsairobo** [comment]
See https://github.com/bonsairobo/feldspar-editor/commit/47208edd9c79f1046b36e3df2bc9cf5f64d9bea8

**Comment by dcz-self** [comment]
Thanks!
